version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 10
  pre_build:
    commands:
      # run 'npm install' using versions in package-lock.json
      - npm install
      - npm ci
  build:
    commands:
      - npm run build
artifacts:
  files:
    - start_service.sh
    - stop_service.sh
    - server.js
    - package.json
    - appspec.yml
    - 'node_modules/**/*'